[GLOBAL]
pants_version = "2.15.0"

backend_packages.add = [
  "pants.backend.python",
]

[source]
root_patterns = ["python", "airflow"]


[python]
interpreter_constraints = ["==3.10.*"]
enable_resolves = true

[python-bootstrap]
search_path = [
    "%(homedir)s/.xmake/packages/p/python/3.10.6/e357df3d007a461995be04740991afd2/bin/",
    "<PATH>"
]

